<template>

	<div>

		<Spinner v-if="ready == false"/>

		<div class="row mt-3 justify-content-center" v-if="ready == true && $parent.$parent.$parent.user != null">

			<div class="col-12">

				<form @submit="addApp">

					<div class="form-group">

						<label for="apps.name" class="sr-only">User</label>
						<input type="text" id="apps.name" class="form-control" placeholder="Name" maxlength='250' required>

					</div>

					<div class="form-group">

						<label for="apps.description" class="sr-only">User</label>
						<textarea class="form-control" id="apps.description" rows="5" cols="50" placeholder="Description" maxlength='250' required></textarea>

					</div>

					<div class="form-group">

						<h5 class="text-center">TOKEN WILL BE AUTOGENERATED</h5>

					</div>

					<div class="form-group">

						<div class="input-group">

							<div class="custom-file">

								<input type="file" class="custom-file-input" id="imageFile" @change="updateUploadImg">
								<label class="custom-file-label" for="imageFile">Choose file</label>

							</div>

							<div class="input-group-append">

								<button type="button" class="btn btn-danger" @click="clearFileInput"><i class="fas fa-trash"></i></button>

							</div>

						</div>

					</div>

					<div class="form-group">

						<div class="form-row">

							<div class="col justify-content-center align-items-center">

								<h5 class="text-center">App image</h5>

								<div id="uploadImgDiv" class="justify-content-center align-items-center">

									<img class="app_img" src="https://awesometracker.ddns.net/userImg/default.png">

								</div>

							</div>

						</div>

					</div>

					<div class="form-group" v-if="$parent.$parent.$parent.user['userCategories.name'] == 'ADMIN' || $parent.$parent.$parent.apps">

						<div class="form-row" v-if="$parent.$parent.$parent.user['userCategories.name'] == 'ADMIN'">

							<div class="col-12 mb-3 col-md-3 mb-md-0">

								<label for="apps.categoryCode" class="sr-only">Category</label>
								<select id='apps.categoryCode' class="form-control" required>

									<option v-for='category in categories' v-bind:key="category" v-bind:value='category["appCategories.code"]'>{{category['appCategories.name']}}</option>

								</select>

							</div>

							<div class="col-12 mb-3 col-md-3 mb-md-0">

								<label for="apps.userCode" class="sr-only">App owner</label>
								<select id='apps.userCode' class="form-control" required>

									<option v-for='user in users' v-bind:key="user" v-bind:value='user["users.code"]'>{{user['users.name']}}</option>

								</select>

							</div>

							<div class="col-12 mb-3 col-md-3 mb-md-0">

								<label for="apps.statusCode" class="sr-only">App status</label>
								<select id='apps.statusCode' class="form-control" required>

									<option v-for='stat in status' v-bind:key="stat" v-bind:value='stat["status.code"]'>{{stat['status.name']}}</option>

								</select>

							</div>

							<div class="col-12 mb-3 col-md-3 mb-md-0">

								<label for="apps.visibility" class="sr-only">App visibility</label>
								<select id='apps.visibility' class="form-control" required>

									<option value='public'>public</option>
									<option value='private'>private</option>

								</select>

							</div>

						</div>

						<div class="form-row" v-else>

							<div class="col-12 mb-3 col-md-6 mb-md-0">

								<label for="apps.statusCode" class="sr-only">App status</label>
								<select id='apps.statusCode' class="form-control" required>

									<option v-for='stat in status' v-bind:key="stat" v-bind:value='stat["status.code"]'>{{stat['status.name']}}</option>

								</select>

							</div>

							<div class="col-12 mb-3 col-md-6 mb-md-0">

								<label for="users.visibility" class="sr-only">App visibility</label>
								<select id='users.visibility' class="form-control" required>

									<option value='public'>public</option>
									<option value='private'>private</option>

								</select>

							</div>

						</div>

					</div>

					<button type="submit" class="btn btn-block btn-success mb-2">Create app</button>

				</form>

			</div>

		</div>

	</div>

</template>

<script>

	import Axios from 'axios'
	import Swal from 'sweetalert2'
	import Spinner from './Spinner.vue';

	export default {

		name: 'Apps_AddApp',
		components: {

			Spinner

		},
		data() {

			return {

				ready: false,
				categories: [],
				users: [],
				status: []

			}

		},
		methods: {

			clearFileInput: function (e) {

				e.preventDefault();

				document.getElementById('imageFile').value = '';
				this.updateUploadImg();

			},

			updateUploadImg: async function () {

				try {

					let validExtensions = ['gif', 'jpeg', 'jpg', 'png'];

					if (document.getElementById('imageFile').files[0]) {

						let file = document.getElementById('imageFile');
						let extension = file.files[0].name.split('.')[file.files[0].name.split('.').length - 1];

						if (validExtensions.includes(extension)) {

							let reader = new FileReader();

							reader.onload = function() {

								document.getElementById('uploadImgDiv').childNodes[0].remove();

								let imgNode = document.createElement('img');
								imgNode.classList.add('user_img');
								imgNode.src = reader.result;

								document.getElementById('uploadImgDiv').appendChild(imgNode);

							};

							reader.readAsDataURL(file.files[0]);

						} else {

							throw new Error();

						}

					} else {

						document.getElementById('uploadImgDiv').childNodes[0].remove();

						let imgNode = document.createElement('img');
						imgNode.classList.add('user_img');
						imgNode.src = this.user['users.imageURL'];

						document.getElementById('uploadImgDiv').appendChild(imgNode);

					}

				} catch (e) {

					document.getElementById('uploadImgDiv').childNodes[0].remove();

					let textNode = document.createElement('h5');
					let text = document.createTextNode('Invalid URL or file provided');
					textNode.appendChild(text);

					document.getElementById('uploadImgDiv').appendChild(textNode);

				}

			},
			addApp: async function (e) {

				e.preventDefault();

				let ok = true;
				let message = '';
				let formData = new FormData();

				for (let i = 0; i < document.forms[0].length - 1; i++) {

					if (document.forms[0].elements[i].value == '') {

						continue;

					} else {

						if (document.forms[0].elements[i].id == 'imageFile') {

							formData.append(document.forms[0].elements[i].id, document.forms[0].elements[i].files[0]);

						} else {

							formData.append(document.forms[0].elements[i].id, document.forms[0].elements[i].value);

						}

					}

					if (/name|description/.test(document.forms[0].elements[i].id)) {

						document.forms[0].elements[i].value = document.forms[0].elements[i].value.substring(0, 250);

					}

					if (/imageFile/.test(document.forms[0].elements[i].id)) {

						let validExtensions = ['jpeg', 'jpg', 'gif', 'png'];
						let extension = document.forms[0].elements[i].files[0].name.split('.')[ document.forms[0].elements[i].files[0].name.split('.').length - 1];

						if (!validExtensions.includes(extension)) {

							ok = false;
							message = 'Invalid file extension';
							break;

						}

					}

				}

				if (ok) {

					let result = await Axios.post(`https://awesometracker.ddns.net/dashboard/addApp`, formData);

					if (result.data.status == 'ok') {

						await Swal.fire({

							timer: 3000,
							title: 'Done',
							text: result.data.msg,
							icon: 'success'

						});

						this.$router.go(-1);

					} else {

						await Swal.fire({

							title: 'Some error',
							text: result.data.msg,
							icon: 'error'

						});

					}

				} else {

					await Swal.fire({

						showConfirmButton: false,
						timer: 5000,
						title: 'Invalid values',
						text: message,
						icon: 'info'

					});

				}


			}

		},
		async created() {

			this.ready = false;

			this.status = [];

			let result = await Axios.get(`https://awesometracker.ddns.net/dashboard/data/12?orderBy=status.code`);

			if (result.data.status == 'ok') {

				this.status = result.data.data;

			} else {

				await Swal.fire({

					showConfirmButton: false,
					timer: 5000,
					title: 'Invalid session',
					text: 'Redirecting',
					icon: 'warning'

				});

				this.$router.go(-1);

				return;

			}

			if (this.$parent.$parent.$parent.user['userCategories.name'] == 'ADMIN') {

				this.users = [];

				result = await Axios.get(`https://awesometracker.ddns.net/dashboard/data/4?orderBy=users.code`);

				if (result.data.status == 'ok') {

					this.users = result.data.data;
					this.users.shift();

				}

				this.categories = [];

				result = await Axios.get(`https://awesometracker.ddns.net/dashboard/data/13?orderBy=appCategories.code`);

				if (result.data.status == 'ok') {

					this.categories = result.data.data;

				}

			}

			this.ready = true;

		}

	}

</script>

<style>

	.app_img {

		width: 100%;
		height: 100%;
		border-radius: 50%;

	}

</style>